[project]
name = "ai-op-copilot"
version = "0.1.0"
description = "CLI para consultar modelos Mistral"
readme = "README.md"
authors = [
    { name = "Pedro Santo", email = "pedro.esanto@pedroesanto.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "mistralai==2.10.0",
    "pydantic==2.13.5",
    "python-dotenv==1.2.3",
    "uuid>=1.30",
]

[project.scripts]
ai-op-copilot = "ai_op_copilot.main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
  venvPath = "."
  venv = ".venv"
